services:
  expose:
    image: expose-server:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:${PORT}
    environment:
      port: ${PORT}
      domain: ${DOMAIN}
      username: ${ADMIN_USERNAME}
    restart: always
    volumes:
      - ./database/expose.db:/root/.expose
